### ISSUE TITLE
About scale path

### ISSUE THREAD

**Issue by StetchPlane** [StevenGrove/DynamicHead#5]
https://github.com/StevenGrove/DynamicHead/blob/5097e2bd21e36fbdcab90f0b23b67162157e46bb/cvpods/layers/dynamic_conv.py#L363
https://github.com/StevenGrove/DynamicHead/blob/5097e2bd21e36fbdcab90f0b23b67162157e46bb/cvpods/layers/dynamic_conv.py#L386

请问,在融合scale path得到的特征图时,我看到代码中设置scale_weight默认为0,那岂不是在训练过程中就没用到scale_path呢?

**Comment by StevenGrove** [comment]
The self.scale_weight has gradients and will change during the training phase. The zero initialization aims to stabilize the gradients of features at the very beginning iterations.

**Comment by StetchPlane** [comment]
非常感谢您的回答.
